export { createTelegramRpcClient } from './telegramClient.js';
export type {
  TelegramChatHistoryFactsChat,
  TelegramCountMessagesInIntervalsInput,
  TelegramCountMessagesInIntervalsOutput,
  TelegramEnsureHistoryCoverageInput,
  TelegramEnsureHistoryCoverageOutput,
  TelegramFileRef,
  TelegramGetChatHistoryFactsInput,
  TelegramGetChatHistoryFactsOutput,
  TelegramGetChatInput,
  TelegramGetChatOutput,
  TelegramGetHistoryCoverageInput,
  TelegramGetHistoryCoverageOutput,
  TelegramHistoryChat,
  TelegramHistoryCoverageSegment,
  TelegramHistoryFetchPageRequest,
  TelegramHistoryFetchPageResult,
  TelegramHistoryInterval,
  TelegramHistoryListChatsRequest,
  TelegramListRecentMessagesOutput,
  TelegramListRecentMessagesInput,
  TelegramReadChat,
  TelegramReadMessage,
  TelegramSearchMessagesInput,
  TelegramSearchMessagesOutput
} from './contracts.js';
