/* global console, process */

import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { join, relative } from 'node:path';

const root = process.cwd();
const failures = [];

const sourceFiles = listFiles(root).filter((file) => !ignored(file));
const tsFiles = sourceFiles.filter((file) => file.endsWith('.ts'));
const vueFiles = sourceFiles.filter((file) => file.endsWith('.vue'));

auditNamingConventions(sourceFiles);
auditCrossDomainSchemaImports(tsFiles);
auditNoPublicProcedureDtoExports(tsFiles);
auditNoModuleRpcClientFacades(tsFiles);
auditModuleRpcFolders(tsFiles);
auditNoContextProcedureApi(tsFiles);
auditTablePrefixes();
auditExtensionBoundaries(tsFiles);
auditDockerfileWorkspacePackageCopies();
auditDateContract(sourceFiles);
auditTdlibContractGeneration(sourceFiles);
auditScopedVueComponentStyles(vueFiles, sourceFiles);

if (failures.length > 0) {
  for (const failure of failures) {
    console.error(failure);
  }
  process.exitCode = 1;
} else {
  console.log('source-audit: ok');
}

function auditNamingConventions(files) {
  const directories = new Set();

  for (const file of files) {
    const rel = toRel(file);
    const parts = rel.split('/');
    for (let index = 0; index < parts.length - 1; index += 1) {
      directories.add(parts.slice(0, index + 1).join('/'));
    }

    if (isExternalNamingContractFile(rel)) {
      continue;
    }

    const fileName = parts.at(-1) ?? '';
    const stem = projectFileStem(fileName);
    if (!/^(?:[a-z][A-Za-z0-9]*|[0-9]+[A-Za-z0-9]*)$/.test(stem)) {
      failures.push(`project file names must use camelCase: ${rel}`);
    }
  }

  for (const directory of directories) {
    for (const segment of directory.split('/')) {
      if (segment.startsWith('.')) {
        continue;
      }
      if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(segment)) {
        failures.push(`project directory names must use kebab-case: ${directory}`);
        break;
      }
    }
  }
}

function projectFileStem(fileName) {
  let stem = fileName;
  for (;;) {
    const extension = [
      '.vue',
      '.ts',
      '.mjs',
      '.js',
      '.json',
      '.md',
      '.yml',
      '.yaml',
      '.html',
      '.css',
      '.sql'
    ].find((candidate) => stem.endsWith(candidate));
    if (extension === undefined) {
      break;
    }
    stem = stem.slice(0, -extension.length);
  }

  for (;;) {
    const suffix = ['.test', '.config', '.d'].find((candidate) => stem.endsWith(candidate));
    if (suffix === undefined) {
      break;
    }
    stem = stem.slice(0, -suffix.length);
  }

  return stem;
}

function isExternalNamingContractFile(rel) {
  const fileName = rel.split('/').at(-1) ?? '';
  const externalFileNames = new Set([
    'AGENTS.md',
    'Dockerfile',
    'docker-compose.yml',
    'drizzle.config.ts',
    'eslint.config.js',
    'package-lock.json',
    'package.json',
    'tsconfig.json',
    'vite.config.ts'
  ]);

  if (fileName.startsWith('.') || externalFileNames.has(fileName)) {
    return true;
  }
  if (rel === 'packages/claude-plugin/bun.lock') {
    return true;
  }
  if (/\/drizzle\/(?:meta\/)?(?:_journal|\d{4}[_-]).*\.(?:json|sql)$/.test(`/${rel}`)) {
    return true;
  }

  return false;
}

function auditCrossDomainSchemaImports(files) {
  const schemaImports = [];

  for (const file of files) {
    const rel = toRel(file);
    const owner = packageOwner(rel);
    const source = readFileSync(file, 'utf8');

    for (const specifier of schemaImports) {
      if (!source.includes(specifier)) {
        continue;
      }

      const schemaOwner = specifier.split('/')[1];
      if (owner !== schemaOwner) {
        failures.push(`cross-domain storage schema import is not allowed: ${rel} -> ${specifier}`);
      }
    }
  }
}

function auditNoPublicProcedureDtoExports(files) {
  for (const file of files) {
    const rel = toRel(file);
    if (!/packages\/[^/]+\/src\/framework\/index\.ts$/.test(rel)) {
      continue;
    }

    const source = readFileSync(file, 'utf8');
    const procedureDtoExport =
      /export\s+type\s+\{[^}]*\b[A-Za-z0-9]+(?:Input|Output)\b[^}]*\}\s+from\s+['"]\.\/procedures\//s;
    if (procedureDtoExport.test(source)) {
      failures.push(`public RPC surface must not export procedure Input/Output DTO types: ${rel}`);
    }
  }
}

function auditNoModuleRpcClientFacades(files) {
  const forbiddenFiles = new Set([]);

  for (const file of files) {
    const rel = toRel(file);
    if (forbiddenFiles.has(rel)) {
      failures.push(`module RPC clients must be generated by defineModule: ${rel}`);
    }
  }
}

function auditModuleRpcFolders(files) {
  for (const file of files) {
    const rel = toRel(file);
    if (
      /^packages\/telegram\/src\/rpc\/(?:index|setup)\.ts$/.test(rel) ||
      /^packages\/telegram\/src\/rpc\/procedures\//.test(rel)
    ) {
      failures.push(`module RPC folder must contain direct procedure files only: ${rel}`);
    }
  }

  for (const file of files) {
    const rel = toRel(file);
    if (rel === 'packages/framework/src/module.ts') {
      continue;
    }
    if (!rel.startsWith('packages/') || !file.endsWith('.ts')) {
      continue;
    }
    const source = readFileSync(file, 'utf8');
    if (/defineModule\s*</.test(source)) {
      failures.push(`module definitions must not pass explicit defineModule generics: ${rel}`);
    }
  }
}

function auditNoContextProcedureApi(files) {
  const forbiddenTokens = [
    'context' + 'Query',
    'context' + 'Mutation',
    'context' + 'ForInternalRpcCall'
  ];

  for (const file of files) {
    const rel = toRel(file);
    if (rel === 'scripts/sourceAudit.mjs') {
      continue;
    }

    const source = readFileSync(file, 'utf8');
    for (const token of forbiddenTokens) {
      if (source.includes(token)) {
        failures.push(`module procedures must use injected resources, not context API: ${rel}`);
      }
    }
  }
}

function auditTablePrefixes() {
  const schemas = [
    {
      file: join(root, 'packages/telegram/src/database/storageSchema.ts'),
      prefix: 'telegram_'
    }
  ].filter((schema) => existsSync(schema.file));

  for (const schema of schemas) {
    const source = readFileSync(schema.file, 'utf8');
    const tableNames = [...source.matchAll(/pgTable\(\s*['"]([^'"]+)['"]/g)].map(
      (match) => match[1]
    );

    if (tableNames.length === 0) {
      failures.push(`schema declares no pgTable tables: ${toRel(schema.file)}`);
      continue;
    }

    for (const tableName of tableNames) {
      if (!tableName.startsWith(schema.prefix)) {
        failures.push(
          `table ${tableName} in ${toRel(schema.file)} must use prefix ${schema.prefix}`
        );
      }
    }
  }
}

function auditExtensionBoundaries(files) {
  auditNoModuleExtensionEndpoints(files);
  auditControlPlaneSdkHasNoDomainKnowledge(files);
}

function auditNoModuleExtensionEndpoints(files) {
  const domainRpcPrefixes = [];
  const forbiddenTokens = ['registerExtension', 'listExtensions'];

  for (const file of files) {
    const rel = toRel(file);
    if (!domainRpcPrefixes.some((prefix) => rel.startsWith(prefix))) {
      continue;
    }

    const source = readFileSync(file, 'utf8');
    for (const token of forbiddenTokens) {
      if (source.includes(token)) {
        failures.push(`domain RPC must not expose a local extension registry: ${rel} -> ${token}`);
      }
    }
  }
}

function auditDockerfileWorkspacePackageCopies() {
  const dockerfile = readFileSync(join(root, 'Dockerfile'), 'utf8');
  const workspacePackage = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
  const workspaces = new Set(
    (workspacePackage.workspaces ?? []).filter((workspace) => !isCurrentModuleWorkspace(workspace))
  );
  const copiedPackages = [
    ...dockerfile.matchAll(/COPY packages\/([^/]+)\/package\.json packages\/\1\/package\.json/g)
  ]
    .map((match) => `packages/${match[1]}`)
    .filter((workspace) => !isCurrentModuleWorkspace(workspace));

  for (const workspace of workspaces) {
    if (!copiedPackages.includes(workspace)) {
      failures.push(`Dockerfile must copy workspace package manifest: ${workspace}`);
    }
  }

  for (const copiedPackage of copiedPackages) {
    if (!workspaces.has(copiedPackage)) {
      failures.push(`Dockerfile copies non-workspace package manifest: ${copiedPackage}`);
    }
    if (!existsSync(join(root, copiedPackage, 'package.json'))) {
      failures.push(`Dockerfile copies missing package manifest: ${copiedPackage}`);
    }
  }
}

function isCurrentModuleWorkspace(workspace) {
  return (
    workspace === 'packages/framework' ||
    workspace === 'packages/registry' ||
    workspace === 'packages/gateway' ||
    workspace === 'packages/telemetry' ||
    workspace === 'packages/control-plane' ||
    workspace === 'packages/telegram' ||
    workspace === 'packages/history-sync'
  );
}

function auditControlPlaneSdkHasNoDomainKnowledge(files) {
  const forbiddenTokens = ['telegram.', 'history-sync.', 'controlPlane.', '@agentg/telegram'];

  for (const file of files) {
    const rel = toRel(file);
    if (!rel.startsWith('packages/control-plane-sdk/src/')) {
      continue;
    }
    const source = readFileSync(file, 'utf8');
    for (const token of forbiddenTokens) {
      if (source.includes(token)) {
        failures.push(`Control Plane SDK must stay mechanical: ${rel} -> ${token}`);
      }
    }
  }
}

function auditDateContract(files) {
  auditTelegramDateStorageContract();
  auditControlPlaneEventDateContract(files);
}

function auditTelegramDateStorageContract() {
  const telegramGeneratedSchema = readFileSync(
    join(root, 'packages/telegram/src/database/storageSchema.ts'),
    'utf8'
  );
  const telegramGeneratedMigration = readFileSync(
    join(root, 'packages/telegram/drizzle/0000_telegram_tdlib_schema.sql'),
    'utf8'
  );
  if (
    !/\bdate:\s*timestamp\('date',\s*\{\s*withTimezone:\s*true\s*\}\)/.test(telegramGeneratedSchema)
  ) {
    failures.push('Telegram generated schema must store TDLib message date as timestamptz');
  }
  if (!/"date"\s+timestamp with time zone/.test(telegramGeneratedMigration)) {
    failures.push('Telegram generated migration must store TDLib message date as timestamptz');
  }

  for (const rel of [
    'packages/telegram/src/store/message.ts',
    'packages/telegram/src/history/messageCounts.ts'
  ]) {
    const source = readFileSync(join(root, rel), 'utf8');
    if (/getTime\(\)\s*\/\s*1000/.test(source)) {
      failures.push(`Telegram message storage must keep Date values as timestamptz: ${rel}`);
    }
  }
}

function auditControlPlaneEventDateContract(files) {
  for (const file of files) {
    const rel = toRel(file);
    if (
      !rel.startsWith('packages/control-plane/src/') &&
      !rel.startsWith('packages/control-plane-sdk/src/') &&
      !rel.startsWith('packages/history-sync/control-plane/') &&
      !rel.startsWith('packages/telegram/control-plane/')
    ) {
      continue;
    }
    if (!/\.(ts|vue)$/.test(rel)) {
      continue;
    }
    const source = readFileSync(file, 'utf8');
    if (/occurredAt\??:\s*Date\s*\|\s*string/.test(source)) {
      failures.push(`Control Plane browser event state must use ISO strings: ${rel}`);
    }
  }
}

function auditTdlibContractGeneration(files) {
  const storageReviewPath = join(root, 'packages/tdlib-docs/src/data/tdlibStorageReview.json');
  const oldCoveragePath = join(root, 'docs/04-data/telegram-tdlib-schema/coverage.json');
  const dbSchemaGenerator = readFileSync(
    join(root, 'scripts/telegramDbSchemaGenerate.mjs'),
    'utf8'
  );

  if (!existsSync(storageReviewPath)) {
    failures.push(
      'TDLib storage review must exist: packages/tdlib-docs/src/data/tdlibStorageReview.json'
    );
  } else {
    const storageReview = JSON.parse(readFileSync(storageReviewPath, 'utf8'));
    if (storageReview.version !== 2) {
      failures.push('TDLib storage review must use version 2');
    }
    if (!Array.isArray(storageReview.tables) || storageReview.tables.length === 0) {
      failures.push('TDLib storage review must contain schema-design table definitions');
    }
    if (
      !storageReview.tables?.every(
        (table) => typeof table.name === 'string' && Array.isArray(table.columns)
      )
    ) {
      failures.push('TDLib storage review tables must include column definitions');
    }
    auditTdlibStorageReviewPolicy(storageReview);
    auditTdlibStorageReviewParserContract(storageReviewPath);
  }

  if (existsSync(oldCoveragePath)) {
    failures.push(
      'TDLib coverage.json is obsolete; use tdlibStorageReview.json for DB schema design'
    );
  }
  auditNoTdlibMarkdownArtifacts(files);
  auditTelegramWireBoundary(files);
  if (dbSchemaGenerator.includes('tables.md')) {
    failures.push('Telegram DB schema generator must read tdlibStorageReview.json, not tables.md');
  }
  if (dbSchemaGenerator.includes('contract.json')) {
    failures.push('Telegram DB schema generator must not read the old TDLib contract');
  }
  if (!dbSchemaGenerator.includes('tdlibStorageReview.json')) {
    failures.push('Telegram DB schema generator must read tdlibStorageReview.json');
  }

  const forbiddenTokens = [
    `tdlib-${'data-model'}-audit.mjs`,
    `tdlib-${'field-routing'}-generate.mjs`,
    `tdlib-${'field-routing'}.catalog.json`,
    `tdlib-${'field-routing'}.generated.md`,
    `tdlib:${'field-routing'}:generate`,
    `telegram-${'tdlib-schema'}-artifacts-generate.mjs`,
    `scripts/tdlib/${'overrides'}.json`,
    `tdlib:${'contract'}:generate`
  ];

  for (const file of files) {
    const rel = toRel(file);
    if (ignored(file) || rel === 'package-lock.json') {
      continue;
    }
    if (!/\.(json|md|mjs|ts)$/.test(rel)) {
      continue;
    }

    const source = readFileSync(file, 'utf8');
    for (const token of forbiddenTokens) {
      if (source.includes(token)) {
        failures.push(`old TDLib routing artifact reference is not allowed: ${rel} -> ${token}`);
      }
    }
  }
}

function auditTelegramWireBoundary(files) {
  const boundaryPrefixes = [];

  for (const file of files) {
    const rel = toRel(file);
    if (!boundaryPrefixes.some((prefix) => rel === prefix || rel.startsWith(prefix))) {
      continue;
    }

    const source = readFileSync(file, 'utf8');
    if (source.includes('/tdlib-schema/')) {
      failures.push(
        `Telegram live storage path must use generated wire types, not local schemas: ${rel}`
      );
    }
  }
}

function auditNoTdlibMarkdownArtifacts(files) {
  const schemaRoot = 'docs/04-data/telegram-tdlib-schema/';

  for (const file of files) {
    const rel = toRel(file);
    if (rel.startsWith(schemaRoot)) {
      failures.push(`old TDLib contract artifact is obsolete: ${rel}`);
    }
  }
}

function auditTdlibStorageReviewPolicy(storageReview) {
  const allowedColumnTypes = new Set([
    'bigint',
    'boolean',
    'bytea',
    'double precision',
    'integer',
    'jsonb',
    'text',
    'timestamp with time zone'
  ]);
  const allowedColumnRoles = new Set(['primary-key', 'foreign-key', 'data']);

  for (const table of storageReview.tables ?? []) {
    const primaryKeyColumns = [];
    for (const column of table.columns ?? []) {
      const columnName = String(column.name ?? '');
      if (columnName === 'raw' || columnName.startsWith('raw_') || columnName.endsWith('_raw')) {
        failures.push(
          `TDLib storage review must not expose raw storage columns: ${table.name}.${columnName}`
        );
      }
      if (!allowedColumnTypes.has(String(column.pgType ?? ''))) {
        failures.push(
          `TDLib storage review column has unsupported pgType: ${table.name}.${columnName}`
        );
      }
      const role = String(column.role ?? '');
      if (!allowedColumnRoles.has(role)) {
        failures.push(
          `TDLib storage review column has unsupported role: ${table.name}.${columnName}`
        );
      }
      if (role === 'primary-key') {
        primaryKeyColumns.push(columnName);
      }
      if (!Array.isArray(column.sourceFields)) {
        failures.push(
          `TDLib storage review column must declare sourceFields: ${table.name}.${columnName}`
        );
      }
    }
    if (primaryKeyColumns.length === 0) {
      failures.push(`TDLib storage review table must declare a primary key: ${table.name}`);
    }
  }
}

function auditTdlibStorageReviewParserContract(storageReviewPath) {
  const tsxBinary = join(
    root,
    'node_modules',
    '.bin',
    process.platform === 'win32' ? 'tsx.cmd' : 'tsx'
  );
  if (!existsSync(tsxBinary)) {
    failures.push('source-audit requires node_modules/.bin/tsx for TDLib storage parser checks');
    return;
  }

  const code = [
    '(async () => {',
    "  const { readStorageReviewState } = await import('./packages/tdlib-docs/src/server/storageReview.ts');",
    `  await readStorageReviewState(${JSON.stringify(storageReviewPath)});`,
    '})().catch((error) => {',
    '  console.error(error instanceof Error ? error.stack : error);',
    '  process.exit(1);',
    '});'
  ].join('\n');

  try {
    execFileSync(tsxBinary, ['-e', code], {
      cwd: root,
      encoding: 'utf8',
      stdio: 'pipe'
    });
  } catch (error) {
    failures.push(`TDLib storage review must pass the dev-server parser: ${execErrorText(error)}`);
  }
}

function execErrorText(error) {
  const parts = [];
  if (typeof error === 'object' && error !== null) {
    const stderr = 'stderr' in error ? error.stderr : undefined;
    const stdout = 'stdout' in error ? error.stdout : undefined;
    if (typeof stderr === 'string' && stderr.trim().length > 0) {
      parts.push(stderr.trim());
    }
    if (typeof stdout === 'string' && stdout.trim().length > 0) {
      parts.push(stdout.trim());
    }
  }
  if (error instanceof Error) {
    parts.push(error.message);
  }

  return parts.join('\n');
}

function auditScopedVueComponentStyles(vueFiles, sourceFiles) {
  const auditedPrefixes = [
    'packages/control-plane/src/',
    'packages/control-plane-sdk/src/',
    'packages/history-sync/control-plane/',
    'packages/telegram/control-plane/'
  ];

  for (const file of sourceFiles) {
    const rel = toRel(file);
    if (!auditedPrefixes.some((prefix) => rel.startsWith(prefix))) {
      continue;
    }
    if (!/\.(css|ts|vue)$/.test(rel)) {
      continue;
    }
    if (rel === 'packages/control-plane/src/main.ts') {
      continue;
    }

    const source = readFileSync(file, 'utf8');
    if (/import\s+['"][^'"]+\.css['"]/.test(source)) {
      failures.push(`control-plane composition must not import global CSS: ${rel}`);
    }
  }

  for (const file of vueFiles) {
    const rel = toRel(file);
    if (!auditedPrefixes.some((prefix) => rel.startsWith(prefix))) {
      continue;
    }

    const source = readFileSync(file, 'utf8');
    for (const match of source.matchAll(/<style\b([^>]*)>([\s\S]*?)<\/style>/g)) {
      const attrs = match[1];
      if (!/\bscoped\b/.test(attrs)) {
        failures.push(`Vue component styles must be scoped: ${rel}`);
      }
      if (match[2].includes('@apply') && !match[2].includes('@reference "tailwindcss";')) {
        failures.push(`Vue component @apply blocks must reference Tailwind: ${rel}`);
      }
      auditStyleBlockContainsOnlyApply(rel, source, match);
    }

    if (/\B(?::class|v-bind:class)\s*=/.test(source)) {
      failures.push(`Vue component templates must not use dynamic class bindings: ${rel}`);
    }

    for (const match of source.matchAll(/\bclass\s*=\s*(["'])(.*?)\1/g)) {
      const className = match[2].trim();
      if (className.length === 0) {
        failures.push(`Vue component class must be a single semantic name: ${rel}`);
        continue;
      }
      if (/\s/.test(className)) {
        failures.push(`Vue component class must contain one semantic name: ${rel} -> ${className}`);
      }
    }
  }
}

function auditStyleBlockContainsOnlyApply(rel, source, match) {
  const startLine = source.slice(0, match.index).split('\n').length;
  const lines = match[2].split('\n');
  lines.forEach((line, index) => {
    const trimmed = line.trim();
    if (
      trimmed.length === 0 ||
      trimmed.startsWith('@apply ') ||
      trimmed.startsWith('@reference ') ||
      trimmed.startsWith('.') ||
      trimmed.startsWith('}') ||
      trimmed.endsWith('{') ||
      trimmed.startsWith('/*') ||
      trimmed.startsWith('*')
    ) {
      return;
    }
    failures.push(
      `Vue component style blocks may contain selectors and @apply only: ${rel}:${String(startLine + index + 1)}`
    );
  });
}

function listFiles(directory) {
  const entries = readdirSync(directory, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) {
      if (ignoredDirectory(path)) {
        continue;
      }
      files.push(...listFiles(path));
      continue;
    }
    if (entry.isFile()) {
      files.push(path);
    }
  }

  return files;
}

function ignoredDirectory(directory) {
  const rel = toRel(directory);
  return (
    rel === 'node_modules' ||
    rel === '.claude' ||
    rel === '.codegraph' ||
    rel === '.tmp' ||
    rel === 'dist' ||
    rel === 'dist-control-plane' ||
    rel === 'dist-server' ||
    rel === 'output' ||
    rel === 'packages/framework' ||
    rel === 'packages/registry' ||
    rel === 'packages/gateway' ||
    rel === 'packages/control-plane' ||
    rel === 'packages/telegram' ||
    rel === 'packages/history-sync' ||
    rel === 'td-data' ||
    rel.endsWith('/node_modules') ||
    rel.endsWith('/.claude') ||
    rel.endsWith('/.codegraph') ||
    rel.endsWith('/.tmp') ||
    rel.endsWith('/dist') ||
    rel.endsWith('/dist-control-plane') ||
    rel.endsWith('/dist-server') ||
    rel.endsWith('/output') ||
    rel.endsWith('/packages/framework') ||
    rel.endsWith('/packages/registry') ||
    rel.endsWith('/packages/gateway') ||
    rel.endsWith('/packages/control-plane') ||
    rel.endsWith('/packages/telegram') ||
    rel.endsWith('/packages/history-sync') ||
    rel.endsWith('/td-data') ||
    rel === '.git' ||
    rel.endsWith('/.git')
  );
}

function ignored(file) {
  const rel = toRel(file);
  return (
    rel.includes('/node_modules/') ||
    rel.includes('/.claude/') ||
    rel.includes('/.codegraph/') ||
    rel.includes('/.tmp/') ||
    rel.includes('/dist/') ||
    rel.includes('/dist-control-plane/') ||
    rel.includes('/dist-server/') ||
    rel.includes('/output/') ||
    rel.includes('/packages/framework/') ||
    rel.includes('/packages/registry/') ||
    rel.includes('/packages/gateway/') ||
    rel.includes('/packages/control-plane/') ||
    rel.includes('/packages/telegram/') ||
    rel.includes('/packages/history-sync/') ||
    rel.includes('/td-data/') ||
    rel.startsWith('node_modules/') ||
    rel.startsWith('.claude/') ||
    rel.startsWith('.codegraph/') ||
    rel.startsWith('.tmp/') ||
    rel.startsWith('dist/') ||
    rel.startsWith('dist-control-plane/') ||
    rel.startsWith('dist-server/') ||
    rel.startsWith('output/') ||
    rel.startsWith('packages/framework/') ||
    rel.startsWith('packages/registry/') ||
    rel.startsWith('packages/gateway/') ||
    rel.startsWith('packages/control-plane/') ||
    rel.startsWith('packages/telegram/') ||
    rel.startsWith('packages/history-sync/') ||
    rel.startsWith('td-data/')
  );
}

function packageOwner(rel) {
  const match = /^packages\/([^/]+)\//.exec(rel);
  return match?.[1];
}

function toRel(file) {
  return relative(root, file).replaceAll('\\', '/');
}
